services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB = 'portfolio_db'
      - POSTGRES_USER = 'postgres'
      - POSTGRES_PASSWORD = 'postgres'
    volumes:
      - portfolio_postgres:/var/lib/postgresql/data
    ports:
      - "5423:5432"
volumes:
  portfolio_postgres: